application: burgergeddon
version: 1
runtime: go
api_version: go1

handlers:
- url: /images
  static_dir: public/images
- url: /style
  static_dir: public/style
- url: /scripts
  mime_type: text/javascript
  static_dir: public/scripts
- url: /
  script: _go_app
